@baseUrl = http://localhost:3000

POST {{baseUrl}}/produtos/
Content-Type: application/json

{
    "nome": "Nuggets",
    "marca": "Fazenda do Futuro",
    "preco": 26.00,
    "quantidade": 10
}

###
GET {{baseUrl}}/produtos/
?limit=5
&offset=0

###
GET {{baseUrl}}/produtos/1


###
PUT {{baseUrl}}/produtos/2
Content-Type: application/json

{
    "nome": "Hamburguer Defumado",
    "marca": "Sadia",
    "preco": 26.00,
    "quantidade": 4
}

###
DELETE {{baseUrl}}/produtos/3


# Avaliações

###

POST {{baseUrl}}/avaliacoes/
Content-Type: application/json

{
  "nome_Pessoa": "Luana Cardoso",
  "idade": 38,
  "email": "luana@gmail.com",
  "nota": "5",
  "comentario": "Produto excelente! Recomendo a todos.",
  "origem_Animal": false,
  "origem_Vegetal": true,
  "livreDe_Crueldade": true,
  "embalagem_Reciclavel": true,
  "nacional": true,
  "produto_id": 2
}
