@baseUrl = http://localhost:3000

POST {{baseUrl}}/produtos/
Content-Type: application/json

{
    "nome": "Rímel azul",
    "marca": "Vizella",
    "preco": 45.00,
    "quantidade": 1
}

###
GET {{baseUrl}}/produtos/
?limit=5
&offset=0

###
GET {{baseUrl}}/produtos/7


###
PUT {{baseUrl}}/produtos/9
Content-Type: application/json

{
    "nome": "Rímel preto",
    "marca": "Vizella",
    "preco": 45.00,
    "quantidade": 1
}

###
DELETE {{baseUrl}}/produtos/3


# Avaliações

###
POST {{baseUrl}}/avaliacoes/
Content-Type: application/json

{
  "nome_Pessoa": "Luana Cardoso",
  "idade": 38,
  "email": "luanacardoso@gmail.com",
  "nota": "5",
  "comentario": "Produto tem ótima fixação",
  "origem_Animal": false,
  "origem_Vegetal": true,
  "livreDe_Crueldade": true,
  "embalagem_Reciclavel": true,
  "nacional": true,
  "produto_id": 5
}

###
GET {{baseUrl}}/avaliacoes/
?limit=5
&offset=0

###
GET {{baseUrl}}/avaliacoes/1
?limit=5
&offset=0

###
PUT {{baseUrl}}/avaliacoes/1
Content-Type: application/json

{
  "nome_Pessoa": "Luana Cardoso",
  "idade": 38,
  "email": "luanacardoso@gmail.com",
  "nota": "5",
  "comentario": "Produto tem ótima fixação",
  "origem_Animal": false,
  "origem_Vegetal": true,
  "livreDe_Crueldade": true,
  "embalagem_Reciclavel": true,
  "nacional": true,
  "produto_id": 7
}

###
DELETE {{baseUrl}}/avaliacoes/2